/* CREA BASE DE DATOS Y TABLA */
CREATE DATABASE DB_CONTROL_TAREAS
use DB_CONTROL_TAREAS
CREATE TABLE TB_TAREAS ( ID INT IDENTITY (1,1) PRIMARY KEY, TAREA TEXT NOT NULL, ESTADO BIT , USUARIO_CREADOR VARCHAR(100), ASIGNACION VARCHAR(100), FECHA DATE)

/* CONSULTA LAS TAREAS*/
CREATE OR ALTER VIEW VW_MOSTRAR_TAREAS_COMPLETADAS
AS
	SELECT * FROM TB_TAREAS WHERE ESTADO = 1

CREATE OR ALTER VIEW VW_MOSTRAR_TAREAS_PENDIENTES
AS
	SELECT * FROM TB_TAREAS WHERE ESTADO = 0

CREATE PROCEDURE PRC_MOSTRAR_TAREAS
AS
BEGIN 
	SELECT * FROM TB_TAREAS ORDER BY ESTADO DESC
END

EXEC PRC_MOSTRAR_TAREAS
SELECT * FROM VW_MOSTRAR_TAREAS_COMPLETADAS
SELECT * FROM VW_MOSTRAR_TAREAS_PENDIENTES

/* INSERTA UNA NUEVA TAREA*/
ALTER PROCEDURE PRC_INSERTAR_TAREA (@TAREA varchar(max), @USUARIO_CREADOR varchar(100))
	AS
	BEGIN
		DECLARE @EXIST_TAREA varchar(max) = ''
		SELECT @EXIST_TAREA = TAREA FROM TB_TAREAS WHERE TAREA = @TAREA
		IF (@EXIST_TAREA = '')
		BEGIN
			INSERT INTO TB_TAREAS (TAREA, USUARIO_CREADOR) VALUES(@TAREA, @USUARIO_CREADOR)
			print 'si llega 2'
		END
END;

exec PRC_INSERTAR_TAREA "Primera tareas 4", "KEVIN SQL"


/*ACTUALIZA UNA TAREA*/
CREATE PROCEDURE PRC_ACTUALIZAR_TAREA (@TAREA TEXT, @ID INT)
	AS BEGIN
	UPDATE TB_TAREAS SET TAREA = @TAREA WHERE ID = @ID
END;

EXEC PRC_ACTUALIZAR_TAREA "TAREA ACTUALIZADA", 5


/*ELIMINA UNA TAREA*/
CREATE PROCEDURE PRC_ELIMINAR_TAREA (@ID INT)
AS BEGIN
	DELETE FROM TB_TAREAS WHERE ID = @ID
END;

EXEC PRC_ELIMINAR_TAREA 5
SELECT * FROM VW_MOSTRAR_TAREAS
